modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License"

[[mods]] #mandatory

modId="apotheosis" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Apotheosis" #mandatory

description='''
All things that should have been.
'''

[[dependencies.apotheosis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="placebo"
    mandatory=true
    versionRange="[4.4.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.0,)"
    ordering="NONE"
    side="BOTH"